### ISSUE TITLE
MultiCam plugin support

### ISSUE THREAD

**Issue by montyfert** [poulou0/OctoPrint-WebcamExtras#10] opened 2023-05-24 15:07 UTC
hi @poulou0 
 since the last octoprint update full screen button has disapeared . 
thanks 
martin

**Comment by poulou0** [comment] 2023-05-25 10:51
Hey! Thats odd.. Works normally for me on [docker](https://github.com/OctoPrint/octoprint-docker/blob/master/docker-compose.yml) `OctoPrint 1.9.0` and `WebcamExtras 0.0.10`
If you have the [UI Customizer](https://plugins.octoprint.org/plugins/uicustomizer/), uncheck the "Float/Fullscreen webcam" on the settings

Can you give me more info about your installation to narrow it down?

![image](https://github.com/poulou0/OctoPrint-WebcamExtras/assets/48758557/491fe286-0453-4169-b28e-079fed82cabb)

**Comment by montyfert** [comment] 2023-05-25 12:04
hi im running Version 1.9.0 on pi 4 
i dont have ui customizer
when i move my cursor over the webcam i used to get the ful screen button like the picture you provided. but since the update to 1.9.0 all i get is a magnifing glass , not sure if its related but the default camera button is constantly greyed out only my other camera button is available , however when i press the other camera button (top view)it does not do anything on the controll tab ,it changes camera in the dashboard tab.
however i am unable to press the befault camera button to switch back.
![Opera Snapshot_2023-05-25_130146_192 168 0 107](https://github.com/poulou0/OctoPrint-WebcamExtras/assets/74438819/84e17cb3-a4dd-4df3-b2e6-8d188315efa7)
not sure what extra info will help 
thanks for the help 
martin

**Comment by poulou0** [comment] 2023-05-25 12:16
Hmm it looks like you are also using the plugin [MultiCam](https://plugins.octoprint.org/plugins/multicam/)
I haven't tried with that one yet

**Comment by montyfert** [comment] 2023-05-29 22:36
hi if i remove multicam the full screen button comes back and works great , so its sorted
thanks  keep up the good work 
martin

**Comment by Sonic01** [comment] 2023-07-18 13:04
Confirmed this doesn't work with MultiCam, so currently have to decide between having 2 cameras or having 1 camera with the zoom function :(

**Comment by poulou0** [comment] 2023-07-20 11:31
Hello, again.. I got some time in my hands today and installed multicam to have a look..
The version 0.4.0 that I installed worked out of the box.
The buttons on the top-right corner overlap, but the functionality is there!!
![ezgif com-optimize](https://github.com/poulou0/OctoPrint-WebcamExtras/assets/48758557/1cb9bc16-ecb7-47c6-9fe8-266105fb4f56)


Noticed that multicam UI has changed and that version was released in 9 of June
![image](https://github.com/poulou0/OctoPrint-WebcamExtras/assets/48758557/94f548f5-4414-4891-b484-b84664b3aed5)

@Sonic01 @montyfert Can you check please?

**Comment by montyfert** [comment] 2023-07-20 19:59
hi @poulou0  yes its working now thanks.
martin

**Closed as completed** 2023-07-20 20:00 UTC
Labels: enhancement

**Comment by poulou0** [comment] 2023-07-20 20:04
I ended up releasing a new version of my plugin today to iron out some small details..

I'm glad it worked!! If you can spare a star on the repo, I would appreciate it.
I'm trying to get the achievement on github, 😇 thaaanks

**Comment by Sonic01** [comment] 2023-07-20 21:06
not sure what happened, I disabled MultiCam and WebcamExtras and re-enabled them and it seems to work now, though the Fullscreen function seems broken still, I think double clicking used to go full screen AND there used to be a button for it. 

I'll try your v0.11 soon as my current print finishes tomorrow evening!

**Comment by Sonic01** [comment] 2023-07-22 07:22
Confirmed, v0.11 fixes all issues, nice work and great plugin! thanks a lot.

**Comment by poulou0** [comment] 2023-07-24 06:41
Great!! Cheers
